### ISSUE TITLE
UI for Multiple Search Queries 

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-mac#251]
I have been thinking a bit about how the UI for multiple search queries could look like so that it is clear for users how to use the feature.
To avoid confusion, I think it is best to disable the feature by default, meaning that no buttons for adding/deleting additional search fields are shown. Users can activate multiple search queries through a menu option or some key sequence.

## Adding/deleting search fields

I came up with some potential designs, however I am not sure how intuitive they are:

<img width="707" alt="inline" src="https://user-images.githubusercontent.com/1239705/44376032-755a1180-a4ab-11e8-81ee-60e3de41bd26.png">

This option is similar to the [search bar in XCode](https://i.stack.imgur.com/sAR1L.png). It might also be possible to add search options (such as whole words, case insensitivity, ...) also as inline toggle buttons.

<img width="705" alt="separate" src="https://user-images.githubusercontent.com/1239705/44376037-7c811f80-a4ab-11e8-9510-e7a49ec42b34.png">

This looks more according to the [Human Interface Guidelines regarding search fields](https://developer.apple.com/design/human-interface-guidelines/macos/fields-and-labels/search-fields/).

Some things that might need to be discussed regarding the behaviour:
* Should it only be possible to add more search fields if all existing search fields contain some search query? Or should users be able to add a bunch of empty search fields?
    * I think the second option might be more intuitive otherwise it might seem like the feature is broken if it is suddenly not possible anymore to add more search fields.
* Should deleting the last search field be prevented? Or alternatively, if the last search field gets deleted, should the search bar get closed (basically same behaviour like clicking "Done")?
    * Right now, the first option is implemented. Personally I don't have any strong preference.
* Alignment of the find next/previous/all buttons next to the first (topmost) or next to the last (bottommost) search field?

## Highlighting

Matching results for each query are highlighted in different colors.

<img width="182" alt="overlapping highlights" src="https://user-images.githubusercontent.com/1239705/44376048-886ce180-a4ab-11e8-8501-48ff5f4c3475.png">

* Usually, if matching results of the same query overlap, then only the first matching result is highlighted. Should this also be the case if results of different queries overlap? Personally, I feel like it might make sense to show overlapping highlights otherwise some highlights relevant to the user might get lost.
    * Executing "Replace All" on overlapping results is a bit tricky but I think it should work just like applying replace next to the entire document.

I would be happy to hear any thoughts, opinions or different ideas regarding the points mentioned or  the UI for multiple search queries in general.

https://github.com/google/xi-mac/pull/229 https://github.com/google/xi-editor/pull/745

**Comment by jansol** [comment]
* Should users be able to add a bunch of empty search fields?
  * Yes, AFAIK there is no good reason to prevent them from doing so, and it helps with consistency

* Should deleting the last search field be prevented?
  * This feels a lot like footgun safety to me so I'm leaning towards yes, hide the 'remove field' button when there is only one field left. Allowing removing the last search field as a way to close the find bar is redundant and can have unexpected side effects wrt search term restoration.
  * As for styling I kinda like the 1st version better, but looking at the find bar in xcode it's clear that inline buttons are not meant for adding/removing search fields.

* Alignment of the find next/previous/all buttons next to the first (topmost) or next to the last (bottommost) search field?
  * Align with the first search field. Moving UI elements around is generally a bad idea. (If the buttons were on their own line it could make sense to keep the entire line at the bottom... but even then it'd probably feel more natural to keep them at the top)

Another thing that came to mind while looking at the HIG and at Xcode is: should plugins be able to add 'categories' to the search (which could warrant adding a scope bar - although that seems rather clunky as a UI element in and of itself)? Xcode has a search panel for plaintext, symbols, references, callstacks and regular expressions.

**Comment by scholtzan** [comment]
Thanks for your thoughts on this!

Having something like categories provided by sounds for sure interesting and is something I will keep in mind for the future. Though, I am a bit afraid that it might result in a for the user overwhelming UI.

**Comment by jansol** [comment]
Using the standalone style for buttons inside the search field looks a bit out of place IMHO. I'd stick with inline buttons+inline style or external buttons+external style but not mix the two. In this case I might lean towards external because the inline <kbd>+</kbd> is used by xcode for adding special symbols and placeholders.

Also this makes it a bit confusing as to how the previous/next buttons work. Do they jump to the previous/next result of *any* query or (as it the UI layout would hint) to the previous/next result of the topmost query?

There might be some clarity to be won from moving the buttons from the right side to the bottom of the view. Alternatively a vertical divider between the search fields and the buttons could help.

**Comment by scholtzan** [comment]
Right, it might be confusing if the appearance is the same as in Xcode but the behaviour is completely different. I changed it back to having separate <kbd>+</kbd><kbd>-</kbd> buttons:

<img width="748" alt="screen shot 2018-08-26 at 11 56 35" src="https://user-images.githubusercontent.com/1239705/44631893-5d5d1480-a927-11e8-94d7-cd9d4f3c21bc.png">

The previous/next buttons consider the matches of _any_ query. I think aligning these buttoms at the bottom might make that clearer for users.

**Comment by jansol** [comment]
Yeah I think the search fields and <kbd>+</kbd>/<kbd>-</kbd> buttons are fine like this. The only problem I can think of is someone accidentally hitting the <kbd>-</kbd> button while trying to click 'previous'. One way to avoid this would be moving those buttons over to the left side of the search fields (and swapping their order to keep <kbd>+</kbd> closer to the fields), which would also make sense wrt grouping of similar controls (prev/next are immediately next to the search terms, instead of being separated by a column of unrelated buttons).

> I think aligning these buttoms at the bottom might make that clearer for users.

At least that's how most online forms / wizards etc are laid out as well so it kind of makes sense. However this brings us back to the issue of moving UI elements, which is why I suggested a line separator and keeping them at the top. But that's not a perfect solution either.

Another question that came to mind is if/how this interacts with replace? That would add at least another input field and a bunch of buttons.
