### ISSUE TITLE
Can't open files after accidentally trying to open a directory

### ISSUE THREAD

**Issue by jansol** [xi-editor/xi-mac#424]
What it says on the tin. Trying to open a directory using the command line causes xi-mac to activate but seemingly do nothing. Additionally further attempts to open actual files via the command line or the GUI seem to do nothing at all.

**Comment by sharaththegeek** [comment]
Since Xi Editor does not have a Side Bar view like other editors (The other editors handle opening of folders on Command Line by displaying the folder in the Side Bar), I would like to hear suggestions on how we can handle this issue.

My proposal is that unless we intend to create a Side Bar in the near future, we can provide a fix by launching the Open Dialog Box of Xi Editor displaying the folder name given on Command Line. Something like this: 

<img width="568" alt="screenshot 2019-02-05 at 11 43 37 pm" src="https://user-images.githubusercontent.com/33923577/52294710-006a8d80-29a0-11e9-8613-4a93dab0a6fe.png">

<img width="819" alt="screenshot 2019-02-05 at 11 44 02 pm" src="https://user-images.githubusercontent.com/33923577/52294727-082a3200-29a0-11e9-83a0-54906c163ff7.png">

**Comment by jansol** [comment]
A side bar is planned, but currently waiting for some bigger rewrites. This issue is not about actually handling directories, but about not being able to open *anything* after trying to do that.
